coverage:
  status:
    project:
      default:
        # basic
        target: 90%
        threshold: 0.1%
    patch:
      default:
        # basic
        target: 75%
        threshold: 20%
ignore:
  - "examples/"
  - "benches/"