language: rust
dist: focal

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

matrix:
  include:
    - os: linux
      dist: focal
      rust: nightly

script:
  - rustup component add llvm-tools-preview
  - cargo build --all-targets
  - cd observability/ && cargo build && cd ..
  - cd fuzz/ && cargo build && cd ..
  - cd ..
  - cargo test --verbose
  - cargo clean
  - export RUST_LOG=debug
  - export RUSTFLAGS="-Zinstrument-coverage"
  - LLVM_PROFILE_FILE="kvlite-%p-%m.profraw" cargo test --verbose --features "snappy_compression"
  - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
  - bash <(curl -s https://codecov.io/bash) -f lcov.info
